icons = "awesome"

[theme]
name = "solarized-dark"

[theme.overrides]
idle_bg = "#181818"
idle_fg = "#d8d8d8"
info_bg = "#86c1b9"
info_fg = "#181818"
good_bg = "#a1b56c"
good_fg = "#181818"
warning_bg = "#f7ca88"
warning_fg = "#181818"
critical_bg = "#ab4642"
critical_fg = "#181818"
# The rest of the theme settings are left at default.

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_up = false
interval = 5
use_bits = false

[[block]]
block = "battery"
device = "DisplayDevice"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %Y-%m-%d %R"

