outputMode: active
scale: 1
background:
  red: 0.19607843137254901960784313
  green: 0.18823529411764705882352941
  blue: 0.18431372549019607843137254
  opacity: 1.0
fonts:
  sans: sans
widget:
  margin:
    margins:
      - 20
      - 20
      - 20
      - 20
    widget:
      verticalLayout:
        - horizontalLayout:
            - margin:
                margins:
                  - 0
                  - 88
                  - 0
                  - 32
                widget:
                  verticalLayout:
                    - clock:
                        font_size: 128.0
            - verticalLayout:
                - margin:
                    margins:
                      - 256
                      - 0
                      - 12
                      - 8
                    widget:
                      battery:
                        font_size: 24.0
                        length: 600
                - margin:
                    margins:
                      - 256
                      - 0
                      - 0
                      - 8
                    widget:
                      backlight:
                        device: intel_backlight
                        font_size: 24.0
                        length: 600
                - margin:
                    margins:
                      - 256
                      - 0
                      - 0
                      - 8
                    widget:
                      pulseAudio:
                        font_size: 24.0
                        length: 600
        - launcher:
            font_size: 32.0
            length: 1200
            app_opener: ""
            term_opener: ""
            url_opener: ""
