outputMode: active
scale: 1
background:
  red: 0.19607843137254901960784313
  green: 0.18823529411764705882352941
  blue: 0.18431372549019607843137254
  opacity: 1.0
fonts:
  sans: sans
widget:
  margin:
    margins:
      - 10
      - 10
      - 10
      - 10
    widget:
      verticalLayout:
        - launcher:
            font_size: 32.0
            length: 1800
            app_opener: ""
            term_opener: ""
            url_opener: ""
