outputMode: active
scale: 1
fonts:
  sans: sans
widget:
  margin:
    margins:
      - 10
      - 10
      - 10
      - 10
    widget:
      verticalLayout:
        - launcher:
            font_size: 32.0
            length: 1800
            app_opener: ""
            term_opener: ""
            url_opener: ""
background:
  red: 0.0392156862745098
  green: 0.09411764705882353
  blue: 0.1607843137254902
  opacity: 1.0
